apiVersion: apps/v1
kind: Deployment
metadata:
  name: bev-deployment
spec:
  selector:
    matchLabels:
      app: beventos
  template:
    metadata:
      labels:
        app: beventos
    spec:
      containers:
      - name: beventos
        image: joaosantos7293/bev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- #usu-clusterip
apiVersion: v1
kind: Service
metadata:
  name: beventos-service
spec:
  selector:
    app: beventos
  type: ClusterIP 
  ports:
    - name: beventos
      protocol: TCP
      port: 10000
      targetPort: 10000
