apiVersion: v1
kind: Service
metadata:
  name: medicamento-service
spec:
  type: NodePort
  selector:
    app: medicamento
  ports:
    - name: medicamento
      protocol: TCP
      port: 2000
      targetPort: 2000
