apiVersion: v1
kind: Service
metadata:
  name: usuario-service
spec:
  type: NodePort
  selector:
    app: usuario
  ports:
    - name: usuario
      protocol: TCP
      port: 1000
      targetPort: 1000
