apiVersion: apps/v1
kind: Deployment
metadata:
  name: usu-deployment
spec:
  selector:
    matchLabels:
      app: usuario
  template:
    metadata:
      labels:
        app: usuario
    spec:
      containers:
      - name: usuario
        image: joaosantos7293/usu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- #usu-clusterip
apiVersion: v1
kind: Service
metadata:
  name: usu-clusterip
spec:
  selector:
    app: usuario
  ports:
    - name: usuario
      protocol: TCP
      port: 1000
      targetPort: 1000
